### ISSUE TITLE
add documentation to training continuation transform

### ISSUE THREAD

**Issue by bhearsum** [mozilla/firefox-translations-training#306] opened 2023-12-14 19:26 UTC
We've added documentation to most transforms in #305. @gabrielBusta - could you please do the same for training continuation?

**Comment by eu9ene** [comment] 2024-01-08 22:12
Like a dupe of #299 but I'm keeping them both in case something else was meant here @gabrielBusta. We need at least user facing docs on how to use it and maybe more technical details on how it works.

**Closed** 2024-02-26 17:41 UTC
Labels: documentation
