### ISSUE TITLE
Rethink parallelism

### ISSUE THREAD

**Issue by XapaJIaMnu** [mozilla/firefox-translations-training#64] opened 2022-02-02 13:20 UTC
Currently, parallelism is based on the snakemake `--cores` argument. It gets passed down to scripts that also run mutlithreaded:

https://github.com/mozilla/firefox-translations-training/blob/ddba8ebf2558a75a77817c129fd24b5db3ec2987/Snakefile#L287

We do not require snakemake to run jobs in parallel, as our problem is embarassingly parallel and we can just parallelise the jobs themselves.
Currently, eligible for parallelism jobs are `download`, `clean`, `biclean`.
`download` should be sequential to prevent hammering servers too much.
`clean` and `biclean` should be parallel only on a per-corpora basis. We should not try to process multiple corpora in parallel, as it is both IO inefficient and interferes with bicleaner-ai parallelisation.

I propose the snakemake job is run with `--cores 1` and the thread argument to be just passed directly to the scripts:
https://github.com/mozilla/firefox-translations-training/blob/ddba8ebf2558a75a77817c129fd24b5db3ec2987/pipeline/clean/clean-corpus.sh#L17
That do their own parallelisation.
@kpu  wrote a script that parallelises `bicleaner-ai-classify` across `CUDA_VISIBLE_DEVICES` as it doesn't support multi-gpu arguments. Any snakemake interference will cause `bicleaner-ai` to crash sadly.

Would this work for you? Does it interfere with cluster mode?

**Comment by eu9ene** [comment] 2022-02-02 23:04
Limiting parallelism with `--cores 1` in general absolutely interferes with cluster mode.

Let's break it down to several issues you have:

1. Downloading rate limits: like discussed in #61, there are different approaches to fix this issue. We can try to limit parallelism by requesting `threads: workflow.cores`, but it totally makes sense to parallelize downloading from different sources and will definitely break cluster mode by requesting too much of unused resources. I would propose to redesign downloaders to work by importer type, so that we can still parallelize downloading from opus and mtdata for example but it will happen sequentially for each importer.
2. Cleaning already uses `threads: workflow.cores` which means it won't be further parallelized on a local machine. However, it can be parallelized in cluster mode if we have more than one machine available and it makes sense to speed things up.
3. Bicleaner: same as regular cleaning, we should set `threads: workflow.cores`
4. Bicleaner-ai: this is tricky. I managed to nicely parallelize it on our slurm cluster to run on multiple nodes with every thread using 1 GPU. This is very useful because cleaning with full models takes a while. It is harder in local mode because in cluster mode slurm provides `CUDA_VISIBLE_DEVICES` but in local mode we don't have tools to pass correct GPU to a thread. Writing a script that can parallelize bicleaner-ai inside one machine can definitely help for local mode.

We have to think about all three use cases: local, moz-slurm, HPC slurm. I made some changes and moz-slurm works pretty well right now. If we fix bicleaner-ai and tune rule threads to limit parallelism, it seems the local use case will also work fine. HPC one is a different story because of all the time limitations.

**Comment by kpu** [comment] 2022-02-02 23:27
We're being quite abstract here.  

Let's talk about something specific: corpora are not balanced.  Some are much larger than others.  Currently my understanding is that `bicleaner-ai` will take a long time on one GPU for the largest corpus.  This diff allows bicleaner-ai to parallelize over GPUs.  

```
diff --git a/pipeline/bicleaner/bicleaner.sh b/pipeline/bicleaner/bicleaner.sh
index 4371884..d7daece 100644
--- a/pipeline/bicleaner/bicleaner.sh
+++ b/pipeline/bicleaner/bicleaner.sh
@@ -45,9 +45,28 @@ else
   fi
 
   echo "### Classifying"
+  if [ "${type}" == 'bicleaner-ai' ]; then
+       #Convert CUDA_VISIBLE_DEVICES to an array
+       export CUDA_VISIBLE_ARRAY=($CUDA_VISIBLE_DEVICES)
+       #Turn on tensorflow logging in bicleaner-ai
+       export TF_CPP_MIN_LOG_LEVEL=0
+       #This function expects a bicleaner yaml and a 1-based index into the CUDA_VISIBLE_ARRAY
+       #Example: /mnt/nanna0/nbogoych/data/data/fr-en/fr-en-prod/biclean/pack/metadata.yaml index_in_CUDA_VISIBLE_ARRAY+1
+       biclean() {
+               export CUDA_VISIBLE_ARRAY=($CUDA_VISIBLE_DEVICES)
+               export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_ARRAY[$(($2-1))]}
+               bicleaner-ai-classify --scol 2 --tcol 1 - - $1
+       }
+       export -f biclean
+       # {%} is a 1-indexed job slot number from GNU parallel.  We use that as the 1-indexed offset in CUDA_VISIBLE_ARRAY
+       paste <(pigz -dc "${corpus_prefix}.${SRC}.gz") <(pigz -dc "${corpus_prefix}.${TRG}.gz") |
+       parallel -j ${#CUDA_VISIBLE_ARRAY[@]} --pipe -k --block 10M biclean "${pack_dir}"/*.yaml {#} |
+       pigz >"${output_prefix}.scored.gz"
+  else
   paste <(pigz -dc "${corpus_prefix}.${SRC}.gz") <(pigz -dc "${corpus_prefix}.${TRG}.gz") |
     ${cmd} --scol ${scol} --tcol ${tcol} --processes "${threads}"  - - "${pack_dir}"/*.yaml |
     pigz >"${output_prefix}.scored.gz"
+  fi
 
   echo "### Filtering"
   pigz -dc "${output_prefix}.scored.gz" 
```

Now one could argue corpora should be sharded and cleaning each shard would be separate snakemake jobs (and thereby parallelize over a cluster).  The problem is snakemake is quite bad at having more shards for large data and fewer shards for small data, so it's both spamming tiny jobs for tiny corpora and taking a while to clean large corpora.  Unless you know a way to work around that?

**Comment by kpu** [comment] 2022-02-02 23:46
I disagree with @XapaJIaMnu ; snakemake should be allowed to parallelize.  Though there does need to be a way to do mutual exclusion if local is to work.

**Comment by eu9ene** [comment] 2022-02-03 00:37
> This diff allows bicleaner-ai to parallelize over GPUs

@kpu this is great, and I agree, it is definitely useful for cluster mode too to speed up the processing of large corpora. Would you like to create a PR for this change? 

Besides the bicleaner script itself, we also should change requested resources in the snakefile and remove `CUDA_VISIBLE_DEVICES="{gpus}" `:
```
    rule bicleaner:
        ...
        threads: 2 if bicleaner_type == "bicleaner-ai" else workflow.cores
        resources: gpu=gpus_num if bicleaner_type == "bicleaner-ai" else 0
        ... 
        shell: '''bash pipeline/bicleaner/bicleaner.sh \
        ...
```

**Comment by XapaJIaMnu** [comment] 2022-02-03 04:44
The script relies currently on CUDA_VISIBLE_DEVICES, so that it can iterate through all user defined available GPUs, Why do we need to remove the `CUDA_VISIBLE_DEVICES` export? The patch is  currently living in one of my branches, I need to clean up a bit the `bicleaner.sh` and i can submit it tomorrow, but I don't understand the resource bit. The updated task would require one core per GPU, and currently you give it two in total. Do you mean to update it like?
```
threads: gpus_num if bicleaner_type == "bicleaner-ai" else workflow.cores
```

**Comment by kpu** [comment] 2022-02-03 11:22
@eu9ene it's subtle but the script is actually indexing the original `CUDA_VISIBLE_DEVICES`.  So if it comes in with `CUDA_VISIBLE_DEVICES="2 4 5"` then there will be three parallel jobs: slot 1 on GPU 2, slot 2 on GPU 4, and slot 3 on GPU 5.  

As an optimization, GNU parallel should be removed in the case of one GPU to avoid paying for loading time and get full batches.  

(Also if we don't care about determinism, it could use `--line-buffer` here)

**Comment by eu9ene** [comment] 2022-02-03 18:15
>The updated task would require one core per GPU, and currently you give it two in total

Sorry, I meant
```
threads: gpus_num * 2 if bicleaner_type == "bicleaner-ai" else workflow.cores
```
like it's done for training. Extra core per GPU just in case.

> Why do we need to remove the CUDA_VISIBLE_DEVICES export

We need to rethink this one too a bit. Slurm provides `CUDA_VISIBLE_DEVICES` inside the job and we should respect it. So instead of setting our own `GPUS` env, we should just use `CUDA_VISIBLE_DEVICES` everywhere including Marian `-d` flag if it doesn't do this inside. If we want to override what GPUs to use on a local machine, just export different  `CUDA_VISIBLE_DEVICES`.

In this case we should remove `gpus` setting from the config and makefile (not `numgpus`, we still need it for snakemake to request resources) and replace [here](https://github.com/mozilla/firefox-translations-training/blob/ddba8ebf2558a75a77817c129fd24b5db3ec2987/Snakefile#L116) `GPUS="{gpus}"` to `GPUS="${CUDA_VISIBLE_DEVICES}"`.

I hope I didn't miss anything.

**Comment by kpu** [comment] 2022-02-03 18:22
I've seen clusters, including CSD3, recommend claiming a number of cores in proportion to the number of GPUs claimed.  Don't know if slurm is smart enough to put cores on the same NUMA side as the GPU it allocates.  Of course that implicitly means you need to know what that ratio is.  

In any case, for completeness, the script should default to all GPUs if the environment variable is not set.  
```
if [ ${#CUDA_VISIBLE_DEVICES} == 0 ]; then   export CUDA_VISIBLE_DEVICES=$(nvidia-smi --query-gpu=index --format=csv,noheader); fi
```

**Comment by XapaJIaMnu** [comment] 2022-02-03 22:11
PR will materialise tmrw. Sorry for the delay.

**Comment by eu9ene** [comment] 2022-02-04 22:42
@XapaJIaMnu https://github.com/mozilla/firefox-translations-training/pull/67 is merged. Should we close this issue? We have #61 and cleaning doesn't seem to be a problem.

**Comment by XapaJIaMnu** [comment] 2022-02-07 13:16
Once those hotfixes are merged:
https://github.com/mozilla/firefox-translations-training/pull/68
This may be closed.

**Comment by kpu** [comment] 2022-02-07 13:18
Oops that should have been {%} not {#}.  My bad.

**Comment by kpu** [comment] 2022-02-07 19:05
Oh, CUDA_VISIBLE_DEVICES allows commas instead of spaces?  https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
Learn something new every day!
I guess we need `CUDA_VISIBLE_ARRAY=(${CUDA_VISIBLE_DEVICES/,/ })` in both places then (since arrays aren't exported to subshells)

**Comment by eu9ene** [comment] 2022-02-07 19:49
> Does that hack fix it for you @eu9ene?

I see 2 GPUs from 8 utilized now :)

**Comment by kpu** [comment] 2022-02-07 19:58
If I had to guess, the input size is under 2x the block size used for GNU parallel so this is intended behavior?  (We can argue about what the block size should be, ultimately a compromise between loading time and productive time.)

**Comment by eu9ene** [comment] 2022-02-07 21:39
This corpus is pretty big (173404798 sentences, 16 Gb). 

I see that `parallel` is launched with `-j 2`, that's why it uses just two GPUs

```

### Using bicleaner-ai
+ cmd=bicleaner-ai-classify
+ export scol=1
+ scol=1
+ export tcol=2
+ tcol=2
+ '[' -d /data/rw/evgeny/data/pt-en/bicleaner-fix/biclean/pack/en-pt ']'
+ export scol=2
+ scol=2
+ export tcol=1
+ tcol=1
+ echo 0,1,2,3,4,5,6,7
0,1,2,3,4,5,6,7
+ '[' 15 == 0 ']'
+ echo '### Classifying'
### Classifying
+ [[ bicleaner-ai == \b\i\c\l\e\a\n\e\r\-\a\i ]]
+ [[ 15 > 1 ]]
+ CUDA_VISIBLE_ARRAY=(${CUDA_VISIBLE_DEVICES/,/ })
+ export CUDA_VISIBLE_ARRAY
+ export TF_CPP_MIN_LOG_LEVEL=0
+ TF_CPP_MIN_LOG_LEVEL=0
+ export -f biclean
+ pigz
++ pigz -dc /data/rw/evgeny/data/pt-en/bicleaner-fix/clean/corpus/opus_CCMatrix/v1.pt.gz
+ paste /dev/fd/63 /dev/fd/62
+ parallel -j 2 --pipe -k --block 200M biclean /data/rw/evgeny/data/pt-en/bicleaner-fix/biclean/pack/metadata.yaml '{%}'
++ pigz -dc /data/rw/evgeny/data/pt-en/bicleaner-fix/clean/corpus/opus_CCMatrix/v1.en.gz
slurm@mlchead:/data/rw/evgeny/logs/pt-en/bicleaner-fix/bicleaner/opus_CCMatrix$
```

**Comment by eu9ene** [comment] 2022-02-08 17:00
@XapaJIaMnu ^

**Comment by kpu** [comment] 2022-02-08 17:35
`${CUDA_VISIBLE_DEVICES//,/ }`
with two // my bad

**Comment by eu9ene** [comment] 2022-02-08 18:14
right, it works now, thanks! I'll add this fix as a part of slurm support PR.

**Closed by eu9ene** 2022-02-08 18:14 UTC
Labels: optimization
