### ISSUE TITLE
Remove soft hyphen character

### ISSUE THREAD

**Issue by kpu** [mozilla/firefox-translations-training#69] opened 2022-02-07 16:12 UTC
If we're not filtering soft hyphen 0xad already, we should be.  https://github.com/browsermt/bergamot-translator/issues/337

**Comment by marco-c** [comment] 2023-03-23 19:01
Same as #26?

**Comment by gregtatum** [comment] 2024-04-09 21:03
Duplicate of #26.

**Closed by gregtatum** 2024-04-09 21:03 UTC
Labels: quality
