### ISSUE TITLE
NetworkError while fetching log

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-training#200] opened 2023-09-20 20:20 UTC
https://firefox-ci-tc.services.mozilla.com/tasks/F3k0tOoOQMaf9q_vJYqFAg/runs/0/logs/live/public/logs/live.log

<img width="1498" alt="Screenshot 2023-09-20 at 1 18 00 PM" src="https://github.com/mozilla/firefox-translations-training/assets/2486505/a5346c7c-bea5-4103-a5b4-71ba440963e1">

I see this error for the second time for a teacher training task. Last time it didn't go away until the training had finished. This blocks us from monitoring the training progress.

**Comment by gabrielBusta** [comment] 2023-09-21 22:12
I see a `CORS` error in the devtools console:

```
GET
https://firefoxci-websocktunnel.services.mozilla.com/us-central1.5838805491402473905.60099/log/cBTzdzw7Q6e29PZJADQ-bA
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://firefoxci-websocktunnel.services.mozilla.com/us-central1.5838805491402473905.60099/log/cBTzdzw7Q6e29PZJADQ-bA. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 504.
```

When check the URL to see if it is reachable

https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/F3k0tOoOQMaf9q_vJYqFAg/runs/0/artifacts/public%2Flogs%2Flive.log

It redirects me to the same URL I see in the console error

https://firefoxci-websocktunnel.services.mozilla.com/us-central1.5838805491402473905.60099/log/cBTzdzw7Q6e29PZJADQ-bA

I see the message:
```
No client is connected with that id
```

**Comment by marco-c** [comment] 2023-09-21 22:20
The CORS issue might be due to the fact that the response seems to be empty (and so CORS headers are missing).
There is a 504 from https://firefoxci-websocktunnel.services.mozilla.com/.

**Comment by eu9ene** [comment] 2023-09-27 23:15
This might be related. I tried to look at logs for this task https://firefox-ci-tc.services.mozilla.com/tasks/ZHsI6EkhS1efoPX7Hd3niA, got a similar network error and the task restarted. Maybe it restarted even before that but didn't update its status in UI, not sure.

**Comment by eu9ene** [comment] 2023-10-16 21:11
It fails with the same error for a task with the state "exception" https://firefox-ci-tc.services.mozilla.com/tasks/Zdo8zmUARt6Xow5Q_4gqlg

**Comment by bhearsum** [comment] 2023-11-20 20:03
https://mozilla-hub.atlassian.net/browse/RELOPS-723 is the main thing blocking us here, which is tracking getting some sort of cloud logging for these workers, so we can get more information on what might be causing this.

**Comment by marco-c** [comment] 2023-11-21 10:22
@bhearsum maybe stupid idea: what if we had a background script running to periodically upload logs somewhere? This could be also used for implementing experiment tracking.

**Comment by bhearsum** [comment] 2024-01-25 20:35
We just pushed out a new worker image that fixes this for at least one case (where the backend proxy that live logs flow through restarts). Any future occurences of this will need additional debugging, as we don't yet understand any of the other root causes of this.

**Comment by gregtatum** [comment] 2024-02-15 16:43
This is most likely fixed with recent image updates. If this persists we can re-open. Make sure and grab a devtools network tab output.

**Closed by gregtatum** 2024-02-15 16:43 UTC
Labels: bug, taskcluster, blocker, tc-p1
