### ISSUE TITLE
Use ctranslate2 to translate monolingual data

### ISSUE THREAD

**Issue by gregtatum** [mozilla/firefox-translations-training#513] opened 2024-04-03 22:47 UTC
We spend quite a bit of time translating monolingual data, and we could speed it up by using [CTranslate2](https://github.com/OpenNMT/CTranslate2).

https://share.firefox.dev/3U4a0uy

**Comment by marco-c** [comment] 2024-04-04 08:20
Duplicate of #165.

**Closed by marco-c** 2024-04-04 08:20 UTC
Labels: cost & perf
